/**
 * Slugs das páginas de piloto do site antigo (WordPress, `/pilotos/{slug}/`),
 * por id do piloto (`drivers/{id}` = id do ud-sistema). O WP não guardava o id do
 * piloto e o slug era digitado à mão (às vezes pelo nome, às vezes pelo apelido),
 * então não dá pra derivar — o mapa preserva as URLs indexadas/compartilhadas.
 *
 * Gerado em 2026-10-02 cruzando https://www.ultimatedrift.com.br/pilotos/
 * (apelido/número de cada card) com `drivers` em PRD e stage (mesmos ids nos dois).
 * Piloto fora do mapa usa `slugify(apelido)` (ver `assignDriverSlugs`).
 */
export const LEGACY_DRIVER_SLUGS: Readonly<Record<number, string>> = {
  13: "eder-hara",
  15: "francisco-horne",
  20: "guilherme-castagna",
  22: "jorge-garcia",
  23: "lucio-turossi",
  24: "marcelo-machado",
  26: "roger-fujik",
  28: "matheus-sartor",
  34: "peterson-lima",
  36: "rogerio-firmino-dutra",
  37: "sergio-hanazono",
  40: "vinicius-trindade",
  42: "sheriff-barion",
  44: "marcio-kabeca",
  49: "clerisson-souza-ferreira",
  62: "vitor-jatoba",
  66: "cesar-takemura",
  77: "juninho",
  81: "edinho-dos-anjos",
  83: "giovanni-coronado",
  85: "carlos-eduardo-dornelles",
  88: "paulo-bertolino",
  89: "romulo-mesquita",
  90: "douglas-gatto-lisboa",
  93: "gabriel-pacheco",
  100: "felipe-medeiros",
  102: "gustavinho-radical",
  103: "jorge-toledo",
  104: "pedro-sombra",
  109: "marcelo-zaupa",
  119: "lucas-rezende",
  120: "murilo-sobral",
  124: "valentina-piaz-da-silva",
  126: "sergio-longatti",
  130: "lucas-hanazono",
  141: "bruno-landi",
  142: "douglas-santana",
  143: "gilberto-stancov",
  144: "guilherme-facchini",
  145: "gustavo-coronado",
  146: "marcelo-horita",
  154: "haian-camatti",
  158: "nicolas-pandolfi",
  159: "victor-shiguenaga",
  161: "felipe-fujik",
  164: "mateus-callejas",
  166: "mia-orellana",
  167: "natan-gomes",
};
